### ISSUE TITLE
trim doesn't work ltrim/rtrim does

### ISSUE THREAD

**Issue by marcus-at-localhorst** [yusrilhs/str-trim#1]
![chrome_2018-09-27_15-14-07](https://user-images.githubusercontent.com/1337223/46148330-1df84f80-c268-11e8-827f-fe78cb433d57.png)

Chrome 70 beta

thanks for checking

**Comment by yusrilhs** [comment]
Sorry for long response,
I fix this issue in new version.

Thanks
